apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: reops-event-proxy
  namespace: team-researchops
  labels:
    team: team-researchops
spec:
  image: "{{ image }}"
  port: 8080
  liveness:
    path: /internal/health
    initialDelay: 30
  readiness:
    path: /internal/health
    initialDelay: 5
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 80
  ingresses:
    - "https://reops-event-proxy.nav.no"
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      cpu: "1"
      memory: 2048Mi
    requests:
      cpu: "50m"
      memory: 1024Mi
  kafka:
    pool: nav-prod
  accessPolicy:
    outbound:
      external:
        - host: nav-prod-kafka-nav-prod.aivencloud.com
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: kubernetes