apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: analytics-website
  namespace: team-researchops
  labels:
    team: team-researchops
  annotations:
    kafka.nais.io/removeDataWhenResourceIsDeleted: "true"
spec:
  pool: nav-prod
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 1
    partitions: 1
    retentionHours: 168
  acl:
    - team: team-researchops
      application: reops-clean-to-enriched
      access: write
    - team: team-researchops
      application: reops-enriched-to-bigquery
      access: readwrite
    - team: team-researchops
      application: reops-kafka-manager
      access: readwrite